//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenta.CA.Site.CAWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AplicativoFlyWeight", Namespace="http://presenta.com.br/webservices/")]
    [System.SerializableAttribute()]
    public partial class AplicativoFlyWeight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperadorFlyWeight", Namespace="http://presenta.com.br/webservices/")]
    [System.SerializableAttribute()]
    public partial class OperadorFlyWeight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaOperadorFlyWeight", Namespace="http://presenta.com.br/webservices/")]
    [System.SerializableAttribute()]
    public partial class CaOperadorFlyWeight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdOperadorField;
        
        private int StOperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CdOperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NmOperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DsEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdOperador {
            get {
                return this.IdOperadorField;
            }
            set {
                if ((this.IdOperadorField.Equals(value) != true)) {
                    this.IdOperadorField = value;
                    this.RaisePropertyChanged("IdOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StOperador {
            get {
                return this.StOperadorField;
            }
            set {
                if ((this.StOperadorField.Equals(value) != true)) {
                    this.StOperadorField = value;
                    this.RaisePropertyChanged("StOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CdOperador {
            get {
                return this.CdOperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CdOperadorField, value) != true)) {
                    this.CdOperadorField = value;
                    this.RaisePropertyChanged("CdOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NmOperador {
            get {
                return this.NmOperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NmOperadorField, value) != true)) {
                    this.NmOperadorField = value;
                    this.RaisePropertyChanged("NmOperador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DsEmail {
            get {
                return this.DsEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.DsEmailField, value) != true)) {
                    this.DsEmailField = value;
                    this.RaisePropertyChanged("DsEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://presenta.com.br/webservices/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://presenta.com.br/webservices/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://presenta.com.br/webservices/", ConfigurationName="CAWS.CAv2ServiceSoap")]
    public interface CAv2ServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListarAplicativosPorSistemaResult from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ListarAplicativosPorSistema", ReplyAction="*")]
        Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaResponse ListarAplicativosPorSistema(Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaRequest request);
        
        // CODEGEN: Generating message contract since element name ListarParesDeAplicativosResult from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ListarParesDeAplicativos", ReplyAction="*")]
        Presenta.CA.Site.CAWS.ListarParesDeAplicativosResponse ListarParesDeAplicativos(Presenta.CA.Site.CAWS.ListarParesDeAplicativosRequest request);
        
        // CODEGEN: Generating message contract since element name ListarOperadoresResult from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ListarOperadores", ReplyAction="*")]
        Presenta.CA.Site.CAWS.ListarOperadoresResponse ListarOperadores(Presenta.CA.Site.CAWS.ListarOperadoresRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ListarOperadoresAtivosPorAplicativo", ReplyAction="*")]
        Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoResponse ListarOperadoresAtivosPorAplicativo(Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoRequest request);
        
        // CODEGEN: Generating message contract since element name ListarEmailsResult from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ListarEmails", ReplyAction="*")]
        Presenta.CA.Site.CAWS.ListarEmailsResponse ListarEmails(Presenta.CA.Site.CAWS.ListarEmailsRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/DeveTrocarSenha", ReplyAction="*")]
        Presenta.CA.Site.CAWS.DeveTrocarSenhaResponse DeveTrocarSenha(Presenta.CA.Site.CAWS.DeveTrocarSenhaRequest request);
        
        // CODEGEN: Generating message contract since element name senha from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/IsSenhaPadrao", ReplyAction="*")]
        Presenta.CA.Site.CAWS.IsSenhaPadraoResponse IsSenhaPadrao(Presenta.CA.Site.CAWS.IsSenhaPadraoRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/TrocarSenha", ReplyAction="*")]
        Presenta.CA.Site.CAWS.TrocarSenhaResponse TrocarSenha(Presenta.CA.Site.CAWS.TrocarSenhaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ObterTipoAutenticacao", ReplyAction="*")]
        int ObterTipoAutenticacao();
        
        // CODEGEN: Generating message contract since element name login from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/Autenticar", ReplyAction="*")]
        Presenta.CA.Site.CAWS.AutenticarResponse Autenticar(Presenta.CA.Site.CAWS.AutenticarRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/Autorizar", ReplyAction="*")]
        Presenta.CA.Site.CAWS.AutorizarResponse Autorizar(Presenta.CA.Site.CAWS.AutorizarRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ObterPerfil", ReplyAction="*")]
        Presenta.CA.Site.CAWS.ObterPerfilResponse ObterPerfil(Presenta.CA.Site.CAWS.ObterPerfilRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://presenta.com.br/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://presenta.com.br/webservices/ObterInfo", ReplyAction="*")]
        Presenta.CA.Site.CAWS.ObterInfoResponse ObterInfo(Presenta.CA.Site.CAWS.ObterInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAplicativosPorSistemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAplicativosPorSistema", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaRequestBody Body;
        
        public ListarAplicativosPorSistemaRequest() {
        }
        
        public ListarAplicativosPorSistemaRequest(Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarAplicativosPorSistemaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idSistema;
        
        public ListarAplicativosPorSistemaRequestBody() {
        }
        
        public ListarAplicativosPorSistemaRequestBody(int idSistema) {
            this.idSistema = idSistema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAplicativosPorSistemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAplicativosPorSistemaResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaResponseBody Body;
        
        public ListarAplicativosPorSistemaResponse() {
        }
        
        public ListarAplicativosPorSistemaResponse(Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarAplicativosPorSistemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.AplicativoFlyWeight[] ListarAplicativosPorSistemaResult;
        
        public ListarAplicativosPorSistemaResponseBody() {
        }
        
        public ListarAplicativosPorSistemaResponseBody(Presenta.CA.Site.CAWS.AplicativoFlyWeight[] ListarAplicativosPorSistemaResult) {
            this.ListarAplicativosPorSistemaResult = ListarAplicativosPorSistemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarParesDeAplicativosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarParesDeAplicativos", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarParesDeAplicativosRequestBody Body;
        
        public ListarParesDeAplicativosRequest() {
        }
        
        public ListarParesDeAplicativosRequest(Presenta.CA.Site.CAWS.ListarParesDeAplicativosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarParesDeAplicativosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idAplicativo;
        
        public ListarParesDeAplicativosRequestBody() {
        }
        
        public ListarParesDeAplicativosRequestBody(int idAplicativo) {
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarParesDeAplicativosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarParesDeAplicativosResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarParesDeAplicativosResponseBody Body;
        
        public ListarParesDeAplicativosResponse() {
        }
        
        public ListarParesDeAplicativosResponse(Presenta.CA.Site.CAWS.ListarParesDeAplicativosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarParesDeAplicativosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.AplicativoFlyWeight[] ListarParesDeAplicativosResult;
        
        public ListarParesDeAplicativosResponseBody() {
        }
        
        public ListarParesDeAplicativosResponseBody(Presenta.CA.Site.CAWS.AplicativoFlyWeight[] ListarParesDeAplicativosResult) {
            this.ListarParesDeAplicativosResult = ListarParesDeAplicativosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarOperadoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarOperadores", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarOperadoresRequestBody Body;
        
        public ListarOperadoresRequest() {
        }
        
        public ListarOperadoresRequest(Presenta.CA.Site.CAWS.ListarOperadoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarOperadoresRequestBody {
        
        public ListarOperadoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarOperadoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarOperadoresResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarOperadoresResponseBody Body;
        
        public ListarOperadoresResponse() {
        }
        
        public ListarOperadoresResponse(Presenta.CA.Site.CAWS.ListarOperadoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarOperadoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.OperadorFlyWeight[] ListarOperadoresResult;
        
        public ListarOperadoresResponseBody() {
        }
        
        public ListarOperadoresResponseBody(Presenta.CA.Site.CAWS.OperadorFlyWeight[] ListarOperadoresResult) {
            this.ListarOperadoresResult = ListarOperadoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarOperadoresAtivosPorAplicativoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarOperadoresAtivosPorAplicativo", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoRequestBody Body;
        
        public ListarOperadoresAtivosPorAplicativoRequest() {
        }
        
        public ListarOperadoresAtivosPorAplicativoRequest(Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarOperadoresAtivosPorAplicativoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idAplicativo;
        
        public ListarOperadoresAtivosPorAplicativoRequestBody() {
        }
        
        public ListarOperadoresAtivosPorAplicativoRequestBody(string login, string senha, int idAplicativo) {
            this.login = login;
            this.senha = senha;
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarOperadoresAtivosPorAplicativoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarOperadoresAtivosPorAplicativoResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoResponseBody Body;
        
        public ListarOperadoresAtivosPorAplicativoResponse() {
        }
        
        public ListarOperadoresAtivosPorAplicativoResponse(Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarOperadoresAtivosPorAplicativoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.CaOperadorFlyWeight[] ListarOperadoresAtivosPorAplicativoResult;
        
        public ListarOperadoresAtivosPorAplicativoResponseBody() {
        }
        
        public ListarOperadoresAtivosPorAplicativoResponseBody(Presenta.CA.Site.CAWS.CaOperadorFlyWeight[] ListarOperadoresAtivosPorAplicativoResult) {
            this.ListarOperadoresAtivosPorAplicativoResult = ListarOperadoresAtivosPorAplicativoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarEmailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarEmails", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarEmailsRequestBody Body;
        
        public ListarEmailsRequest() {
        }
        
        public ListarEmailsRequest(Presenta.CA.Site.CAWS.ListarEmailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarEmailsRequestBody {
        
        public ListarEmailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarEmailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarEmailsResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ListarEmailsResponseBody Body;
        
        public ListarEmailsResponse() {
        }
        
        public ListarEmailsResponse(Presenta.CA.Site.CAWS.ListarEmailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ListarEmailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.ArrayOfString ListarEmailsResult;
        
        public ListarEmailsResponseBody() {
        }
        
        public ListarEmailsResponseBody(Presenta.CA.Site.CAWS.ArrayOfString ListarEmailsResult) {
            this.ListarEmailsResult = ListarEmailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeveTrocarSenhaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeveTrocarSenha", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.DeveTrocarSenhaRequestBody Body;
        
        public DeveTrocarSenhaRequest() {
        }
        
        public DeveTrocarSenhaRequest(Presenta.CA.Site.CAWS.DeveTrocarSenhaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class DeveTrocarSenhaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idAplicativo;
        
        public DeveTrocarSenhaRequestBody() {
        }
        
        public DeveTrocarSenhaRequestBody(string login, string senha, int idAplicativo) {
            this.login = login;
            this.senha = senha;
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeveTrocarSenhaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeveTrocarSenhaResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.DeveTrocarSenhaResponseBody Body;
        
        public DeveTrocarSenhaResponse() {
        }
        
        public DeveTrocarSenhaResponse(Presenta.CA.Site.CAWS.DeveTrocarSenhaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class DeveTrocarSenhaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeveTrocarSenhaResult;
        
        public DeveTrocarSenhaResponseBody() {
        }
        
        public DeveTrocarSenhaResponseBody(bool DeveTrocarSenhaResult) {
            this.DeveTrocarSenhaResult = DeveTrocarSenhaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsSenhaPadraoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsSenhaPadrao", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.IsSenhaPadraoRequestBody Body;
        
        public IsSenhaPadraoRequest() {
        }
        
        public IsSenhaPadraoRequest(Presenta.CA.Site.CAWS.IsSenhaPadraoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class IsSenhaPadraoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senha;
        
        public IsSenhaPadraoRequestBody() {
        }
        
        public IsSenhaPadraoRequestBody(string senha) {
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsSenhaPadraoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsSenhaPadraoResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.IsSenhaPadraoResponseBody Body;
        
        public IsSenhaPadraoResponse() {
        }
        
        public IsSenhaPadraoResponse(Presenta.CA.Site.CAWS.IsSenhaPadraoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class IsSenhaPadraoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsSenhaPadraoResult;
        
        public IsSenhaPadraoResponseBody() {
        }
        
        public IsSenhaPadraoResponseBody(bool IsSenhaPadraoResult) {
            this.IsSenhaPadraoResult = IsSenhaPadraoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrocarSenhaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrocarSenha", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.TrocarSenhaRequestBody Body;
        
        public TrocarSenhaRequest() {
        }
        
        public TrocarSenhaRequest(Presenta.CA.Site.CAWS.TrocarSenhaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class TrocarSenhaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string novaSenha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idAplicativo;
        
        public TrocarSenhaRequestBody() {
        }
        
        public TrocarSenhaRequestBody(string login, string senha, string novaSenha, int idAplicativo) {
            this.login = login;
            this.senha = senha;
            this.novaSenha = novaSenha;
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrocarSenhaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrocarSenhaResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.TrocarSenhaResponseBody Body;
        
        public TrocarSenhaResponse() {
        }
        
        public TrocarSenhaResponse(Presenta.CA.Site.CAWS.TrocarSenhaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class TrocarSenhaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TrocarSenhaResult;
        
        public TrocarSenhaResponseBody() {
        }
        
        public TrocarSenhaResponseBody(bool TrocarSenhaResult) {
            this.TrocarSenhaResult = TrocarSenhaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Autenticar", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.AutenticarRequestBody Body;
        
        public AutenticarRequest() {
        }
        
        public AutenticarRequest(Presenta.CA.Site.CAWS.AutenticarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class AutenticarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idAplicativo;
        
        public AutenticarRequestBody() {
        }
        
        public AutenticarRequestBody(string login, string senha, int idAplicativo) {
            this.login = login;
            this.senha = senha;
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticarResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.AutenticarResponseBody Body;
        
        public AutenticarResponse() {
        }
        
        public AutenticarResponse(Presenta.CA.Site.CAWS.AutenticarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class AutenticarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AutenticarResult;
        
        public AutenticarResponseBody() {
        }
        
        public AutenticarResponseBody(bool AutenticarResult) {
            this.AutenticarResult = AutenticarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutorizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Autorizar", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.AutorizarRequestBody Body;
        
        public AutorizarRequest() {
        }
        
        public AutorizarRequest(Presenta.CA.Site.CAWS.AutorizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class AutorizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idAplicativo;
        
        public AutorizarRequestBody() {
        }
        
        public AutorizarRequestBody(string login, string senha, int idAplicativo) {
            this.login = login;
            this.senha = senha;
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutorizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutorizarResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.AutorizarResponseBody Body;
        
        public AutorizarResponse() {
        }
        
        public AutorizarResponse(Presenta.CA.Site.CAWS.AutorizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class AutorizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.ArrayOfInt AutorizarResult;
        
        public AutorizarResponseBody() {
        }
        
        public AutorizarResponseBody(Presenta.CA.Site.CAWS.ArrayOfInt AutorizarResult) {
            this.AutorizarResult = AutorizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPerfilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPerfil", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ObterPerfilRequestBody Body;
        
        public ObterPerfilRequest() {
        }
        
        public ObterPerfilRequest(Presenta.CA.Site.CAWS.ObterPerfilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ObterPerfilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idAplicativo;
        
        public ObterPerfilRequestBody() {
        }
        
        public ObterPerfilRequestBody(string login, string senha, int idAplicativo) {
            this.login = login;
            this.senha = senha;
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterPerfilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterPerfilResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ObterPerfilResponseBody Body;
        
        public ObterPerfilResponse() {
        }
        
        public ObterPerfilResponse(Presenta.CA.Site.CAWS.ObterPerfilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ObterPerfilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.ArrayOfInt ObterPerfilResult;
        
        public ObterPerfilResponseBody() {
        }
        
        public ObterPerfilResponseBody(Presenta.CA.Site.CAWS.ArrayOfInt ObterPerfilResult) {
            this.ObterPerfilResult = ObterPerfilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterInfo", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ObterInfoRequestBody Body;
        
        public ObterInfoRequest() {
        }
        
        public ObterInfoRequest(Presenta.CA.Site.CAWS.ObterInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ObterInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idAplicativo;
        
        public ObterInfoRequestBody() {
        }
        
        public ObterInfoRequestBody(string login, string senha, int idAplicativo) {
            this.login = login;
            this.senha = senha;
            this.idAplicativo = idAplicativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterInfoResponse", Namespace="http://presenta.com.br/webservices/", Order=0)]
        public Presenta.CA.Site.CAWS.ObterInfoResponseBody Body;
        
        public ObterInfoResponse() {
        }
        
        public ObterInfoResponse(Presenta.CA.Site.CAWS.ObterInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://presenta.com.br/webservices/")]
    public partial class ObterInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Presenta.CA.Site.CAWS.ArrayOfString ObterInfoResult;
        
        public ObterInfoResponseBody() {
        }
        
        public ObterInfoResponseBody(Presenta.CA.Site.CAWS.ArrayOfString ObterInfoResult) {
            this.ObterInfoResult = ObterInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CAv2ServiceSoapChannel : Presenta.CA.Site.CAWS.CAv2ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAv2ServiceSoapClient : System.ServiceModel.ClientBase<Presenta.CA.Site.CAWS.CAv2ServiceSoap>, Presenta.CA.Site.CAWS.CAv2ServiceSoap {
        
        public CAv2ServiceSoapClient() {
        }
        
        public CAv2ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CAv2ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAv2ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAv2ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.ListarAplicativosPorSistema(Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaRequest request) {
            return base.Channel.ListarAplicativosPorSistema(request);
        }
        
        public Presenta.CA.Site.CAWS.AplicativoFlyWeight[] ListarAplicativosPorSistema(int idSistema) {
            Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaRequest inValue = new Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaRequestBody();
            inValue.Body.idSistema = idSistema;
            Presenta.CA.Site.CAWS.ListarAplicativosPorSistemaResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).ListarAplicativosPorSistema(inValue);
            return retVal.Body.ListarAplicativosPorSistemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.ListarParesDeAplicativosResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.ListarParesDeAplicativos(Presenta.CA.Site.CAWS.ListarParesDeAplicativosRequest request) {
            return base.Channel.ListarParesDeAplicativos(request);
        }
        
        public Presenta.CA.Site.CAWS.AplicativoFlyWeight[] ListarParesDeAplicativos(int idAplicativo) {
            Presenta.CA.Site.CAWS.ListarParesDeAplicativosRequest inValue = new Presenta.CA.Site.CAWS.ListarParesDeAplicativosRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.ListarParesDeAplicativosRequestBody();
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.ListarParesDeAplicativosResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).ListarParesDeAplicativos(inValue);
            return retVal.Body.ListarParesDeAplicativosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.ListarOperadoresResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.ListarOperadores(Presenta.CA.Site.CAWS.ListarOperadoresRequest request) {
            return base.Channel.ListarOperadores(request);
        }
        
        public Presenta.CA.Site.CAWS.OperadorFlyWeight[] ListarOperadores() {
            Presenta.CA.Site.CAWS.ListarOperadoresRequest inValue = new Presenta.CA.Site.CAWS.ListarOperadoresRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.ListarOperadoresRequestBody();
            Presenta.CA.Site.CAWS.ListarOperadoresResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).ListarOperadores(inValue);
            return retVal.Body.ListarOperadoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.ListarOperadoresAtivosPorAplicativo(Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoRequest request) {
            return base.Channel.ListarOperadoresAtivosPorAplicativo(request);
        }
        
        public Presenta.CA.Site.CAWS.CaOperadorFlyWeight[] ListarOperadoresAtivosPorAplicativo(string login, string senha, int idAplicativo) {
            Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoRequest inValue = new Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.ListarOperadoresAtivosPorAplicativoResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).ListarOperadoresAtivosPorAplicativo(inValue);
            return retVal.Body.ListarOperadoresAtivosPorAplicativoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.ListarEmailsResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.ListarEmails(Presenta.CA.Site.CAWS.ListarEmailsRequest request) {
            return base.Channel.ListarEmails(request);
        }
        
        public Presenta.CA.Site.CAWS.ArrayOfString ListarEmails() {
            Presenta.CA.Site.CAWS.ListarEmailsRequest inValue = new Presenta.CA.Site.CAWS.ListarEmailsRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.ListarEmailsRequestBody();
            Presenta.CA.Site.CAWS.ListarEmailsResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).ListarEmails(inValue);
            return retVal.Body.ListarEmailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.DeveTrocarSenhaResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.DeveTrocarSenha(Presenta.CA.Site.CAWS.DeveTrocarSenhaRequest request) {
            return base.Channel.DeveTrocarSenha(request);
        }
        
        public bool DeveTrocarSenha(string login, string senha, int idAplicativo) {
            Presenta.CA.Site.CAWS.DeveTrocarSenhaRequest inValue = new Presenta.CA.Site.CAWS.DeveTrocarSenhaRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.DeveTrocarSenhaRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.DeveTrocarSenhaResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).DeveTrocarSenha(inValue);
            return retVal.Body.DeveTrocarSenhaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.IsSenhaPadraoResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.IsSenhaPadrao(Presenta.CA.Site.CAWS.IsSenhaPadraoRequest request) {
            return base.Channel.IsSenhaPadrao(request);
        }
        
        public bool IsSenhaPadrao(string senha) {
            Presenta.CA.Site.CAWS.IsSenhaPadraoRequest inValue = new Presenta.CA.Site.CAWS.IsSenhaPadraoRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.IsSenhaPadraoRequestBody();
            inValue.Body.senha = senha;
            Presenta.CA.Site.CAWS.IsSenhaPadraoResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).IsSenhaPadrao(inValue);
            return retVal.Body.IsSenhaPadraoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.TrocarSenhaResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.TrocarSenha(Presenta.CA.Site.CAWS.TrocarSenhaRequest request) {
            return base.Channel.TrocarSenha(request);
        }
        
        public bool TrocarSenha(string login, string senha, string novaSenha, int idAplicativo) {
            Presenta.CA.Site.CAWS.TrocarSenhaRequest inValue = new Presenta.CA.Site.CAWS.TrocarSenhaRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.TrocarSenhaRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.novaSenha = novaSenha;
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.TrocarSenhaResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).TrocarSenha(inValue);
            return retVal.Body.TrocarSenhaResult;
        }
        
        public int ObterTipoAutenticacao() {
            return base.Channel.ObterTipoAutenticacao();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.AutenticarResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.Autenticar(Presenta.CA.Site.CAWS.AutenticarRequest request) {
            return base.Channel.Autenticar(request);
        }
        
        public bool Autenticar(string login, string senha, int idAplicativo) {
            Presenta.CA.Site.CAWS.AutenticarRequest inValue = new Presenta.CA.Site.CAWS.AutenticarRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.AutenticarRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.AutenticarResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).Autenticar(inValue);
            return retVal.Body.AutenticarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.AutorizarResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.Autorizar(Presenta.CA.Site.CAWS.AutorizarRequest request) {
            return base.Channel.Autorizar(request);
        }
        
        public Presenta.CA.Site.CAWS.ArrayOfInt Autorizar(string login, string senha, int idAplicativo) {
            Presenta.CA.Site.CAWS.AutorizarRequest inValue = new Presenta.CA.Site.CAWS.AutorizarRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.AutorizarRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.AutorizarResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).Autorizar(inValue);
            return retVal.Body.AutorizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.ObterPerfilResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.ObterPerfil(Presenta.CA.Site.CAWS.ObterPerfilRequest request) {
            return base.Channel.ObterPerfil(request);
        }
        
        public Presenta.CA.Site.CAWS.ArrayOfInt ObterPerfil(string login, string senha, int idAplicativo) {
            Presenta.CA.Site.CAWS.ObterPerfilRequest inValue = new Presenta.CA.Site.CAWS.ObterPerfilRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.ObterPerfilRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.ObterPerfilResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).ObterPerfil(inValue);
            return retVal.Body.ObterPerfilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presenta.CA.Site.CAWS.ObterInfoResponse Presenta.CA.Site.CAWS.CAv2ServiceSoap.ObterInfo(Presenta.CA.Site.CAWS.ObterInfoRequest request) {
            return base.Channel.ObterInfo(request);
        }
        
        public Presenta.CA.Site.CAWS.ArrayOfString ObterInfo(string login, string senha, int idAplicativo) {
            Presenta.CA.Site.CAWS.ObterInfoRequest inValue = new Presenta.CA.Site.CAWS.ObterInfoRequest();
            inValue.Body = new Presenta.CA.Site.CAWS.ObterInfoRequestBody();
            inValue.Body.login = login;
            inValue.Body.senha = senha;
            inValue.Body.idAplicativo = idAplicativo;
            Presenta.CA.Site.CAWS.ObterInfoResponse retVal = ((Presenta.CA.Site.CAWS.CAv2ServiceSoap)(this)).ObterInfo(inValue);
            return retVal.Body.ObterInfoResult;
        }
    }
}
